Repository open-mpi/mtt, pull requests merged in 2018-11, with the labels that each got.

#754 Fixes duration bug with interrupted copytree
  pyclient/pymtt.py
  pylib/System/TestDef.py
  pylib/Tools/Executor/sequential.py
  pylib/Utilities/Copytree.py
  pylib/Utilities/Watchdog.py
Labels: Python Client

#760 Fixes #758 IUDatabase plugin not writing data
  pylib/Stages/Reporter/IUDatabase.py
Labels: Python Client, bug

#761 Since we now pass the description in, this is not needed
  pylib/Stages/Reporter/JunitXML.py
Labels: Python Client, bug

#764 Doxypypy for doxygen interepreter
  docs/Doxyfile
Labels: Code Cleanup, Python Client

#766 Fixes #744, removes --no-reporter, adds wildcard
  pyclient/pymtt.py
  pylib/System/TestDef.py
  pylib/System/test_TestDef.py
Labels: Python Client
