Repository open-mpi/mtt, pull requests merged in 2018-08, with the labels that each got.

#684 Minor updates
  pylib/Stages/Reporter/JunitXML.py
  pylib/Utilities/ExecuteCmd.py
  pylib/Utilities/Logger.py
  pylib/Utilities/MPIVersion.py
Labels: Code Cleanup, Python Client, bug, enhancement

#690 Cleanup the TestDef discovery code
  .travis.yml
  pyclient/pymtt.py
Labels: Code Cleanup, bug

#687 Fixed return values of ExecuteCmd, and with how TextFile reporter interprets them
  pylib/Stages/Reporter/TextFile.py
  pylib/Utilities/ExecuteCmd.py
Labels: Python Client

#692 Fixes #674 -- scratch for writing reporter files
  pylib/Stages/Reporter/JunitXML.py
  pylib/Stages/Reporter/TextFile.py
  tests/bat/default_check_profile.ini
  tests/bat/default_check_profile.sh
Labels: Python Client

#699 Related to #695 Remove unneeded print of plugin-name for harasser
  pylib/System/TestDef.py
Labels: Python Client

#701 Fixes #694 Recreate env_modules_python.py when link is broken
  pylib/Utilities/ModuleCmd.py
Labels: Python Client

#700 Fixes #696 Sequential.py now fixes output format of plugins
  pylib/Tools/Executor/sequential.py
Labels: Python Client

#702 Two more invalid stderr formatting fixed in sequential.py
  pylib/Tools/Executor/sequential.py
Labels: Python Client
