Repository open-mpi/mtt, pull requests merged in 2019-02, with the labels that each got.

#782 added the test-results-analyzer jenkins plugin
  tests/jenkins/plugins.txt
Labels: Dockerfile

#783 added postbuild-task plugin
  tests/jenkins/plugins.txt
Labels: Dockerfile

#784 Added Copy plugin
  pylib/Utilities/Copy.py
  pylib/Utilities/Copy.yapsy-plugin
Labels: Python Client, enhancement

#786 Fix for using ompi with --no-shell and srun
  pylib/Tools/Launcher/SLURM.py
Labels: Python Client, enhancement

#789 configTest no longer called between stages
  pylib/System/TestDef.py
  pylib/Tools/Executor/sequential.py
Labels: Python Client

#791 Documentation Update
  condaEnv.yml
  docs/_layouts/default.html
  docs/pages/environment_setup.md
Labels: Documentation, Python Client

#799 Fixes #798 moved fh var from global to instance
  pylib/Stages/Reporter/TextFile.py
Labels: Python Client
