Repository open-mpi/mtt, pull requests merged in 2019-10, with the labels that each got.

#864 COR-12724: updated jenkins container version to 2.198
  tests/jenkins/Dockerfile
  tests/jenkins/plugins.txt
Labels: Dockerfile

#868 #867 fixed TypeError in IPMITool plugin
  pylib/Tools/CNC/IPMITool.py
Labels: Python Client

#871 Capture slurm jobid in ExecuteCmd
  pylib/Utilities/ExecuteCmd.py
Labels: Python Client, enhancement
